name: replicate_json
description: A Dart package for Replicate.
version: 1.0.0
repository: https://github.com/Samffprice/replicate-json#Readme.md

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
